default: &default
  adapter: postgresql
  encode: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: miniapp_autoseg_development

test:
  <<: *default
  database: miniapp_autoseg_test

production:
  <<: *default
  database: miniapp_autoseg_production
  username: miniapp_autoseg
  password: <%= ENV['GAME_EVALUATION_DATABASE_PASSWORD'] %>
